'use client'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { api, token } from '../lib/api'

type Zone={id:string,name:string,comment:string,private_zone:boolean,record_count:number,created_at?:string}
type Record={id:string,name:string,type:string,value:string,ttl:number,routing_policy:string}
const nav=['Dashboard','Hosted zones','Traffic policies','Health checks','Resolver','Profiles']
const recordTypes=['A','AAAA','CNAME','TXT','MX','NS','PTR','SRV','CAA']

function Modal({title,children,onClose}:{title:string,children:React.ReactNode,onClose:()=>void}){return <div className="overlay" role="dialog"><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon" onClick={onClose}>×</button></div>{children}</div></div>}
function Toast({message}:{message:string}){return <div className="toast">✓ {message}</div>}
function Button({children,onClick,kind='primary',type='button',disabled=false}:{children:React.ReactNode,onClick?:()=>void,kind?:string,type?:'button'|'submit',disabled?:boolean}){return <button type={type} onClick={onClick} disabled={disabled} className={`btn ${kind}`}>{children}</button>}

export default function Home(){
 const [ready,setReady]=useState(false),[user,setUser]=useState<any>(null),[email,setEmail]=useState('admin@example.com'),[password,setPassword]=useState('demo'),[section,setSection]=useState('Hosted zones'),[zones,setZones]=useState<Zone[]>([]),[zone,setZone]=useState<Zone|null>(null),[records,setRecords]=useState<Record[]>([]),[query,setQuery]=useState(''),[recordQuery,setRecordQuery]=useState(''),[type,setType]=useState(''),[loading,setLoading]=useState(false),[modal,setModal]=useState<null|'zone'|'record'|'delete-zone'|'delete-record'>(null),[editing,setEditing]=useState<any>(null),[toast,setToast]=useState(''),[error,setError]=useState(''),[dark,setDark]=useState(false),[selected,setSelected]=useState<string[]>([])
 const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),3200)}
 const loadZones=async()=>{setLoading(true);try{const d=await api(`/hosted-zones?q=${encodeURIComponent(query)}`);setZones(d.items)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 const loadRecords=async(z:Zone)=>{setLoading(true);try{const d=await api(`/hosted-zones/${z.id}/records?q=${encodeURIComponent(recordQuery)}&type=${type}`);setRecords(d.items)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{setDark(localStorage.getItem('r53_theme')==='dark');if(!token()){setReady(true);return} api('/auth/session').then(d=>{setUser(d.user);loadZones()}).catch(()=>localStorage.removeItem('r53_token')).finally(()=>setReady(true))},[])
 useEffect(()=>{if(user&&!zone)loadZones()},[query])
 useEffect(()=>{if(zone)loadRecords(zone)},[recordQuery,type])
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('r53_theme',dark?'dark':'light')},[dark])
 useEffect(()=>{const shortcut=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement).tagName))return;if(e.key==='Escape')setModal(null);if(e.key.toLowerCase()==='n'&&!modal){setEditing(null);setModal(zone?'record':'zone')}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut)},[zone,modal])
 const login=async(e:FormEvent)=>{e.preventDefault();setError('');try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('r53_token',d.token);setUser(d.user);loadZones()}catch(e:any){setError(e.message)}}
 const logout=async()=>{await api('/auth/logout',{method:'POST'}).catch(()=>{});localStorage.removeItem('r53_token');setUser(null);setZone(null)}
 const saveZone=async(e:FormEvent)=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const body={name:f.get('name'),comment:f.get('comment'),private_zone:f.get('private')==='on'};try{if(editing)await api(`/hosted-zones/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/hosted-zones',{method:'POST',body:JSON.stringify(body)});setModal(null);setEditing(null);loadZones();notify(`Hosted zone ${editing?'updated':'created'} successfully`)}catch(e:any){setError(e.message)}}
 const saveRecord=async(e:FormEvent)=>{e.preventDefault();if(!zone)return;const f=new FormData(e.currentTarget as HTMLFormElement);const body={name:f.get('name'),type:f.get('type'),value:f.get('value'),ttl:Number(f.get('ttl')),routing_policy:f.get('routing_policy')};try{if(editing)await api(`/hosted-zones/${zone.id}/records/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await api(`/hosted-zones/${zone.id}/records`,{method:'POST',body:JSON.stringify(body)});setModal(null);setEditing(null);loadRecords(zone);loadZones();notify(`Record ${editing?'updated':'created'} successfully`)}catch(e:any){setError(e.message)}}
 const remove=async()=>{try{if(modal==='delete-zone'){await api(`/hosted-zones/${editing.id}`,{method:'DELETE'});setZone(null);loadZones();notify('Hosted zone deleted')}else if(zone){await api(`/hosted-zones/${zone.id}/records/${editing.id}`,{method:'DELETE'});loadRecords(zone);loadZones();notify('Record deleted')}setModal(null);setEditing(null)}catch(e:any){setError(e.message)}}
 const setTheme=()=>setDark(v=>!v)
 const exportZone=async(format:'json'|'bind')=>{if(!zone)return;try{const d=await api(`/hosted-zones/${zone.id}/export?format=${format}`);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([d.content],{type:format==='json'?'application/json':'text/plain'}));a.download=`${zone.name}.${format==='json'?'json':'zone'}`;a.click();URL.revokeObjectURL(a.href);notify(`Exported ${format.toUpperCase()} file`)}catch(e:any){setError(e.message)}}
 const importZone=async(file?:File)=>{if(!zone||!file)return;try{const format=file.name.toLowerCase().endsWith('.json')?'json':'bind';const d=await api(`/hosted-zones/${zone.id}/import`,{method:'POST',body:JSON.stringify({format,content:await file.text()})});loadRecords(zone);loadZones();notify(`Imported ${d.imported} record${d.imported===1?'':'s'}${d.skipped?`; ${d.skipped} skipped`:''}`)}catch(e:any){setError(e.message)}}
 const bulkDelete=async()=>{if(!zone||!selected.length)return;try{const d=await api(`/hosted-zones/${zone.id}/records/bulk-delete`,{method:'POST',body:JSON.stringify({record_ids:selected})});setSelected([]);loadRecords(zone);loadZones();notify(`Deleted ${d.deleted} record${d.deleted===1?'':'s'}`)}catch(e:any){setError(e.message)}}
 if(!ready)return <div className="splash">Loading Route 53…</div>
 if(!user)return <main className="login"><div className="login-card"><img className="aws-logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/960px-Amazon_Web_Services_Logo.svg.png" alt="Amazon Web Services"/><h1>Sign in to AWS Console</h1><p>Use any email and password to enter this Route 53 demo.</p>{error&&<div className="alert">{error}</div>}<form onSubmit={login}><label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label><Button type="submit">Sign in</Button></form><small>This is a mocked sign-in experience.</small></div></main>
 const placeholder=section!=='Hosted zones';
 return <div className="console"><header><div className="brand"><img className="brand-logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/960px-Amazon_Web_Services_Logo.svg.png" alt="AWS"/></div><span className="services">Services</span><div className="top-search">⌕ <span>Search</span></div><div className="top-right"><button title="Toggle dark mode" onClick={setTheme}>{dark?'☀ Light':'◐ Dark'}</button> ◉ {user.account_id}　▾　 <button onClick={logout}>Sign out</button></div></header><aside><div className="service-title">Route 53</div>{nav.map(n=><button key={n} onClick={()=>{setSection(n);if(n==='Hosted zones')setZone(null)}} className={section===n?'active':''}>{n}</button>)}<hr/><button>Registered domains</button><button>Domains</button></aside><main className="content">
 {error&&<div className="alert dismiss" onClick={()=>setError('')}>{error} <b>×</b></div>}
 {placeholder?<div className="placeholder"><div className="placeholder-icon">◌</div><h1>{section}</h1><p>This Route 53 capability is ready for your next iteration.</p><Button onClick={()=>setSection('Hosted zones')}>Go to hosted zones</Button></div>:zone?<RecordsView zone={zone} records={records} loading={loading} recordQuery={recordQuery} type={type} setRecordQuery={setRecordQuery} setType={setType} selected={selected} setSelected={setSelected} back={()=>{setSelected([]);setZone(null)}} add={()=>{setEditing(null);setModal('record')}} edit={(r:Record)=>{setEditing(r);setModal('record')}} remove={(r:Record)=>{setEditing(r);setModal('delete-record')}} exportZone={exportZone} importZone={importZone} bulkDelete={bulkDelete}/>:<ZonesView zones={zones} loading={loading} query={query} setQuery={setQuery} add={()=>{setEditing(null);setModal('zone')}} edit={(z:Zone)=>{setEditing(z);setModal('zone')}} remove={(z:Zone)=>{setEditing(z);setModal('delete-zone')}} open={(z:Zone)=>setZone(z)}/>} 
 </main>
 {modal==='zone'&&<Modal title={editing?'Edit hosted zone':'Create hosted zone'} onClose={()=>setModal(null)}><form className="form" onSubmit={saveZone}><label>Domain name<input name="name" defaultValue={editing?.name||''} placeholder="example.com" required/></label><label>Comment – optional<input name="comment" defaultValue={editing?.comment||''} placeholder="A description for this hosted zone"/></label><label className="check"><input type="checkbox" name="private" defaultChecked={editing?.private_zone}/> Private hosted zone</label><p className="help">Private hosted zones are only visible within associated VPCs.</p><div className="actions"><Button kind="secondary" onClick={()=>setModal(null)}>Cancel</Button><Button type="submit">{editing?'Save changes':'Create hosted zone'}</Button></div></form></Modal>}
 {modal==='record'&&<Modal title={editing?'Edit record':'Create record'} onClose={()=>setModal(null)}><form className="form" onSubmit={saveRecord}><label>Record name<input name="name" defaultValue={editing?.name||zone?.name||''} required/></label><div className="two"><label>Record type<select name="type" defaultValue={editing?.type||'A'}>{recordTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>TTL (seconds)<input name="ttl" type="number" min="0" defaultValue={editing?.ttl||300} required/></label></div><label>Value<textarea name="value" defaultValue={editing?.value||''} placeholder="192.0.2.1" required/></label><label>Routing policy<select name="routing_policy" defaultValue={editing?.routing_policy||'Simple'}><option>Simple</option><option>Weighted</option><option>Latency</option><option>Failover</option></select></label><div className="actions"><Button kind="secondary" onClick={()=>setModal(null)}>Cancel</Button><Button type="submit">{editing?'Save changes':'Create record'}</Button></div></form></Modal>}
 {(modal==='delete-zone'||modal==='delete-record')&&<Modal title={`Delete ${modal==='delete-zone'?'hosted zone':'record'}`} onClose={()=>setModal(null)}><div className="confirm"><p>Are you sure you want to delete <b>{editing?.name}</b>? This action cannot be undone{modal==='delete-zone'&&' and deletes all associated records'}.</p><div className="actions"><Button kind="secondary" onClick={()=>setModal(null)}>Cancel</Button><Button kind="danger" onClick={remove}>Delete</Button></div></div></Modal>}
 {toast&&<Toast message={toast}/>}</div>
}

function ZonesView({zones,loading,query,setQuery,add,edit,remove,open}:any){return <><div className="crumb">Route 53 <span>/</span> Hosted zones</div><div className="title-row"><div><h1>Hosted zones</h1><p>A hosted zone is a container for records that define how you want to route traffic.</p></div><Button onClick={add}>Create hosted zone</Button></div><section className="panel"><div className="toolbar"><div className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter hosted zones"/></div><span>{zones.length} hosted zone{zones.length===1?'':'s'}</span></div>{loading?<div className="state">Loading hosted zones…</div>:zones.length===0?<div className="empty"><h3>No hosted zones found</h3><p>Create a hosted zone to start routing traffic for your domain.</p><Button onClick={add}>Create hosted zone</Button></div>:<table><thead><tr><th>Hosted zone name</th><th>Type</th><th>Record count</th><th>Comment</th><th></th></tr></thead><tbody>{zones.map((z:Zone)=><tr key={z.id}><td><button className="link" onClick={()=>open(z)}>{z.name}</button><small>{z.id}</small></td><td>{z.private_zone?'Private':'Public'}</td><td>{z.record_count}</td><td>{z.comment||'–'}</td><td className="row-actions"><button onClick={()=>edit(z)}>Edit</button><button onClick={()=>remove(z)}>Delete</button></td></tr>)}</tbody></table>}<div className="footer-row">Items per page: 10　 <span>‹　1　›</span></div></section></>}
function RecordsView({zone,records,loading,recordQuery,type,setRecordQuery,setType,selected,setSelected,back,add,edit,remove,exportZone,importZone,bulkDelete}:any){const all=records.length>0&&records.every((r:Record)=>selected.includes(r.id));const toggle=(id:string)=>setSelected((s:string[])=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);return <><div className="crumb"><button onClick={back}>Hosted zones</button> <span>/</span> {zone.name}</div><div className="title-row"><div><h1>{zone.name}</h1><p>Hosted zone details and DNS records <kbd>N</kbd> new record · <kbd>Esc</kbd> close dialog</p></div><div className="title-actions"><label className="btn secondary file-btn">Import<input type="file" accept=".zone,.txt,.bind,.json" onChange={e=>{importZone(e.target.files?.[0]);e.currentTarget.value=''}}/></label><Button kind="secondary" onClick={()=>exportZone('bind')}>Export BIND</Button><Button kind="secondary" onClick={()=>exportZone('json')}>Export JSON</Button><Button onClick={add}>Create record</Button></div></div><div className="tabs"><button className="selected">Records ({records.length})</button><button>Hosted zone details</button><button>Tags</button></div><section className="panel"><div className="toolbar records"><div className="search">⌕ <input value={recordQuery} onChange={e=>setRecordQuery(e.target.value)} placeholder="Filter records"/></div><select value={type} onChange={e=>setType(e.target.value)}><option value="">All record types</option>{recordTypes.map(t=><option key={t}>{t}</option>)}</select>{selected.length>0&&<Button kind="danger" onClick={bulkDelete}>Delete selected ({selected.length})</Button>}</div>{loading?<div className="state">Loading records…</div>:records.length===0?<div className="empty"><h3>No records found</h3><p>Import a BIND/JSON zone file or create a DNS record to begin.</p><Button onClick={add}>Create record</Button></div>:<table><thead><tr><th><input aria-label="Select all records" type="checkbox" checked={all} onChange={e=>setSelected(e.target.checked?records.map((r:Record)=>r.id):[])}/></th><th>Record name</th><th>Type</th><th>Routing policy</th><th>Value/Route traffic to</th><th>TTL</th><th></th></tr></thead><tbody>{records.map((r:Record)=><tr key={r.id}><td><input aria-label={`Select ${r.name}`} type="checkbox" checked={selected.includes(r.id)} onChange={()=>toggle(r.id)}/></td><td>{r.name}</td><td><span className="pill">{r.type}</span></td><td>{r.routing_policy}</td><td className="value">{r.value}</td><td>{r.ttl}</td><td className="row-actions"><button onClick={()=>edit(r)}>Edit</button><button onClick={()=>remove(r)}>Delete</button></td></tr>)}</tbody></table>}<div className="footer-row">Items per page: 25　 <span>‹　1　›</span></div></section></>}
